live_config_reload = true
shell = "pwsh" 

[keyboard]
bindings = [
  { key = "J", mods = "Control | Shift", chars = "\u001b[69;5u" },    # Open Tree in NeoVim
  { key = "F", mods = "Control | Shift", chars = "\u001b[70;5u" },    # Search Grep
  { key = "Tab", mods = "Control", chars = "\u001b[27;5;9~" },	      # Switch Tabs
  { key = "O", mods = "Shift", chars = "\u001b[79;2u" },              # Shift + O for NeoVim
  { key = "S", mods = "Control | Shift", chars = "\u001b[83;5u" },    # Save all
  { key = "Space", mods = "Control", chars = "\u001b[32;5u" },        # Ctrl + Space for Windows
  { key = "I", mods = "Control", chars = "\u001b[73;5u" },            # Ctrl + I
  { key = "Return", mods = "Control | Shift", chars = "\u001b[13;6u" }, # Ctrl + Shift + Enter
  { key = "N", mods = "Control | Shift", action = "SpawnNewInstance" },
]

[window]
padding.x = 0
padding.y = 0
decorations = "Full"
opacity = 1
resize_increments = true
dynamic_padding = false

[font]
size = 11

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 1
# Colors - https://github.com/olimorris/onedarkpro.nvim
[colors.primary]
background  = "#282c34"
foreground  = "#abb2bf"

[colors.normal]
black       = "#282c34"
red         = "#e06c75"
green       = "#98c379"
yellow      = "#e5c07b"
blue        = "#61afef"
magenta     = "#c678dd"
cyan        = "#56b6c2"
white       = "#abb2bf"

[colors.bright]
black       = "#3e4451"
red         = "#e9969d"
green       = "#b3d39c"
yellow      = "#edd4a6"
blue        = "#8fc6f4"
magenta     = "#d7a1e7"
cyan        = "#7bc6d0"
white       = "#c8cdd5"

[colors.selection]
text        = "CellForeground"
background  = "#5c6370"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"	